package com.medibook.notification.entity;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_COMPLETED,
    DOCTOR_APPLICATION_SUBMITTED,
    DOCTOR_APPLICATION_APPROVED,
    DOCTOR_APPLICATION_REJECTED
}
